"""create new tables users and profile

Revision ID: 18c9a41cb2eb
Revises: bb0c283d248e
Create Date: 2023-05-14 23:47:10.568275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c9a41cb2eb'
down_revision = 'bb0c283d248e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
