"""create new tables users and profile

Revision ID: bb0c283d248e
Revises: 02898b2a88d8
Create Date: 2023-05-14 20:17:49.367732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb0c283d248e'
down_revision = '02898b2a88d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
