"""create new tables users and profile

Revision ID: f4f030fa8eaf
Revises: 18c9a41cb2eb
Create Date: 2023-05-14 23:49:03.928975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f030fa8eaf'
down_revision = '18c9a41cb2eb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
