"""unique=True

Revision ID: d3b710f6a46f
Revises: f8c5aa396f6c
Create Date: 2023-05-13 19:15:39.603924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3b710f6a46f'
down_revision = 'f8c5aa396f6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user_registration', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_registration', type_='unique')
    # ### end Alembic commands ###
