"""create new tables users and profile

Revision ID: 40dcb5865a64
Revises: 69eba003493e
Create Date: 2023-05-14 23:52:10.210797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40dcb5865a64'
down_revision = '69eba003493e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
