"""create new tables users and profile

Revision ID: 69eba003493e
Revises: f4f030fa8eaf
Create Date: 2023-05-14 23:51:14.652006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69eba003493e'
down_revision = 'f4f030fa8eaf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
