"""created_time & updated_time

Revision ID: bb98e41efa46
Revises: 540dd7db4c63
Create Date: 2023-05-13 22:21:21.773753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb98e41efa46'
down_revision = '540dd7db4c63'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
